### ISSUE TITLE
CH12: sbt.ResolveException: unresolved dependency: com.typesafe.play#sbt-link;2.2.3: not found

### ISSUE THREAD

**Issue by dusank** [jsuereth/sbt-in-action-examples#11]
```
[info] Loading project definition from D:\ws\sbt-in-action-examples\chapter12\project
[info] Updating {file:/D:/ws/sbt-in-action-examples/chapter12/project/}chapter12-build...
[info] Resolving org.scalastyle#scalastyle-sbt-plugin;0.4.0 ...

M[info] Resolving org.scalastyle#scalastyle_2.10;0.4.0 ...

M[info] Resolving org.scalariform#scalariform_2.10;0.1.4 ...

M[info] Resolving org.scala-lang#scala-library;2.10.0 ...

M[info] Resolving com.github.scopt#scopt_2.10;3.2.0 ...

M[info] Resolving org.scala-lang#scala-library;2.10.3 ...

M[info] Resolving com.typesafe.play#sbt-plugin;2.2.3 ...

M[info] Resolving com.typesafe.play#sbt-link;2.2.3 ...
[warn]  module not found: com.typesafe.play#sbt-link;2.2.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-link/2.2.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/sbt-link/2.2.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\.ivy2\local\com.typesafe.play\sbt-link\2.2.3\ivys\ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/play/sbt-link/2.2.3/sbt-link-2.2.3.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/sbt-link/2.2.3/sbt-link-2.2.3.pom
[info] Resolving com.typesafe.play#play-exceptions;2.2.3 ...
[warn]  module not found: com.typesafe.play#play-exceptions;2.2.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/play-exceptions/2.2.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/play-exceptions/2.2.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\.ivy2\local\com.typesafe.play\play-exceptions\2.2.3\ivys\ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/play/play-exceptions/2.2.3/play-exceptions-2.2.3.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-exceptions/2.2.3/play-exceptions-2.2.3.pom
[info] Resolving com.typesafe.play#routes-compiler_2.10;2.2.3 ...
[warn]  module not found: com.typesafe.play#routes-compiler_2.10;2.2.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/routes-compiler_2.10/2.2.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/routes-compiler_2.10/2.2.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\.ivy2\local\com.typesafe.play\routes-compiler_2.10\2.2.3\ivys\ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/play/routes-compiler_2.10/2.2.3/routes-compiler_2.10-2.2.3.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/routes-compiler_2.10/2.2.3/routes-compiler_2.10-2.2.3.pom
[info] Resolving com.typesafe.play#templates-compiler_2.10;2.2.3 ...
[warn]  module not found: com.typesafe.play#templates-compiler_2.10;2.2.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/templates-compiler_2.10/2.2.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/templates-compiler_2.10/2.2.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\.ivy2\local\com.typesafe.play\templates-compiler_2.10\2.2.3\ivys\ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/play/templates-compiler_2.10/2.2.3/templates-compiler_2.10-2.2.3.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/templates-compiler_2.10/2.2.3/templates-compiler_2.10-2.2.3.pom
[info] Resolving com.typesafe.play#console_2.10;2.2.3 ...
[warn]  module not found: com.typesafe.play#console_2.10;2.2.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/console_2.10/2.2.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/console_2.10/2.2.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\.ivy2\local\com.typesafe.play\console_2.10\2.2.3\ivys\ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/play/console_2.10/2.2.3/console_2.10-2.2.3.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/console_2.10/2.2.3/console_2.10-2.2.3.pom
[info] Resolving com.typesafe#config;1.0.2 ...

M[info] Resolving org.mozilla#rhino;1.7R4 ...

M[info] Resolving com.google.javascript#closure-compiler;v20130603 ...

M[info] Resolving com.google.guava#guava;14.0.1 ...

M[info] Resolving org.json#json;20090211 ...

M[info] Resolving com.github.scala-incubator.io#scala-io-file_2.10;0.4.2 ...

M[info] Resolving com.github.scala-incubator.io#scala-io-core_2.10;0.4.2 ...

M[info] Resolving com.jsuereth#scala-arm_2.10;1.3 ...

M[info] Resolving org.avaje.ebeanorm#avaje-ebeanorm-agent;3.2.1 ...

M[info] Resolving com.h2database#h2;1.3.172 ...

M[info] Resolving org.javassist#javassist;3.18.0-GA ...

M[info] Resolving net.contentobjects.jnotify#jnotify;0.94 ...
[warn]  module not found: net.contentobjects.jnotify#jnotify;0.94
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/net.contentobjects.jnotify/jnotify/0.94/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.contentobjects.jnotify/jnotify/0.94/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\.ivy2\local\net.contentobjects.jnotify\jnotify\0.94\ivys\ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/net/contentobjects/jnotify/jnotify/0.94/jnotify-0.94.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/net/contentobjects/jnotify/jnotify/0.94/jnotify-0.94.pom
[info] Resolving com.typesafe.sbteclipse#sbteclipse-plugin;2.4.0 ...

M[info] Resolving com.typesafe.sbteclipse#sbteclipse-core;2.4.0 ...

M[info] Resolving org.scalaz#scalaz-core_2.10;7.0.2 ...

M[info] Resolving org.scalaz#scalaz-effect_2.10;7.0.2 ...

M[info] Resolving org.specs2#specs2_2.10;2.1.1 ...

M[info] Resolving org.scalaz#scalaz-concurrent_2.10;7.0.2 ...

M[info] Resolving com.eed3si9n#sbt-assembly;0.11.2 ...

M[info] Resolving org.apache.velocity#velocity;1.7 ...

M[info] Resolving commons-collections#commons-collections;3.2.1 ...

M[info] Resolving commons-lang#commons-lang;2.4 ...

M[info] Resolving com.typesafe.sbt#sbt-git;0.6.2 ...

M[info] Resolving org.eclipse.jgit#org.eclipse.jgit.pgm;2.2.0.201212191850-r ...

M[info] Resolving args4j#args4j;2.0.12 ...

M[info] Resolving org.apache.commons#commons-compress;1.3 ...

M[info] Resolving org.eclipse.jgit#org.eclipse.jgit;2.2.0.201212191850-r ...

M[info] Resolving com.jcraft#jsch;0.1.44-1 ...

M[info] Resolving org.eclipse.jgit#org.eclipse.jgit.iplog;2.2.0.201212191850-r ...

M[info] Resolving org.eclipse.jgit#org.eclipse.jgit.ui;2.2.0.201212191850-r ...

M[info] Resolving com.typesafe.sbt#sbt-native-packager;0.7.1 ...

M[info] Resolving org.apache.commons#commons-compress;1.4.1 ...

M[info] Resolving org.tukaani#xz;1.0 ...

M[info] Resolving com.github.mpeltonen#sbt-idea;1.6.0 ...

M[info] Resolving commons-io#commons-io;2.0.1 ...

M[info] Resolving org.scala-lang#scala-library;2.10.4 ...

M[info] Resolving org.scala-sbt#sbt;0.13.5 ...

M[info] Resolving org.scala-sbt#main;0.13.5 ...

M[info] Resolving org.scala-sbt#actions;0.13.5 ...

M[info] Resolving org.scala-sbt#classpath;0.13.5 ...

M[info] Resolving org.scala-lang#scala-compiler;2.10.4 ...

M[info] Resolving org.scala-lang#scala-reflect;2.10.4 ...

M[info] Resolving org.scala-sbt#launcher-interface;0.13.5 ...

M[info] Resolving org.scala-sbt#interface;0.13.5 ...

M[info] Resolving org.scala-sbt#io;0.13.5 ...

M[info] Resolving org.scala-sbt#control;0.13.5 ...

M[info] Resolving org.scala-sbt#completion;0.13.5 ...

M[info] Resolving org.scala-sbt#collections;0.13.5 ...

M[info] Resolving jline#jline;2.11 ...

M[info] Resolving org.scala-sbt#api;0.13.5 ...

M[info] Resolving org.scala-sbt#compiler-integration;0.13.5 ...

M[info] Resolving org.scala-sbt#incremental-compiler;0.13.5 ...

M[info] Resolving org.scala-sbt#logging;0.13.5 ...

M[info] Resolving org.scala-sbt#process;0.13.5 ...

M[info] Resolving org.scala-sbt#relation;0.13.5 ...

M[info] Resolving org.scala-sbt#compile;0.13.5 ...

M[info] Resolving org.scala-sbt#persist;0.13.5 ...

M[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...

M[info] Resolving org.scala-sbt#classfile;0.13.5 ...

M[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.5 ...

M[info] Resolving org.scala-sbt#ivy;0.13.5 ...

M[info] Resolving org.scala-sbt#cross;0.13.5 ...

M[info] Resolving org.apache.ivy#ivy;2.3.0 ...

M[info] Resolving com.jcraft#jsch;0.1.46 ...

M[info] Resolving org.scala-sbt#run;0.13.5 ...

M[info] Resolving org.scala-sbt#task-system;0.13.5 ...

M[info] Resolving org.scala-sbt#tasks;0.13.5 ...

M[info] Resolving org.scala-sbt#tracking;0.13.5 ...

M[info] Resolving org.scala-sbt#cache;0.13.5 ...

M[info] Resolving org.scala-sbt#testing;0.13.5 ...

M[info] Resolving org.scala-sbt#test-agent;0.13.5 ...

M[info] Resolving org.scala-sbt#test-interface;1.0 ...

M[info] Resolving org.scala-sbt#main-settings;0.13.5 ...

M[info] Resolving org.scala-sbt#apply-macro;0.13.5 ...

M[info] Resolving org.scala-sbt#command;0.13.5 ...

M[info] Resolving org.scala-sbt#logic;0.13.5 ...

M[info] Resolving org.scala-sbt#compiler-interface;0.13.5 ...

M[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.5 ...

M[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.5 ...

M[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.5 ...

M[info] Resolving org.scala-lang#jline;2.10.4 ...

M[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.play#sbt-link;2.2.3: not found
[warn]  :: com.typesafe.play#play-exceptions;2.2.3: not found
[warn]  :: com.typesafe.play#routes-compiler_2.10;2.2.3: not found
[warn]  :: com.typesafe.play#templates-compiler_2.10;2.2.3: not found
[warn]  :: com.typesafe.play#console_2.10;2.2.3: not found
[warn]  :: net.contentobjects.jnotify#jnotify;0.94: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: com.typesafe.play#sbt-link;2.2.3: not found
unresolved dependency: com.typesafe.play#play-exceptions;2.2.3: not found
unresolved dependency: com.typesafe.play#routes-compiler_2.10;2.2.3: not found
unresolved dependency: com.typesafe.play#templates-compiler_2.10;2.2.3: not found
unresolved dependency: com.typesafe.play#console_2.10;2.2.3: not found
unresolved dependency: net.contentobjects.jnotify#jnotify;0.94: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:125)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:57)
    at sbt.IvySbt.withIvy(Ivy.scala:98)
    at sbt.IvySbt.withIvy(Ivy.scala:94)
    at sbt.IvySbt$Module.withModule(Ivy.scala:115)
    at sbt.IvyActions$.update(IvyActions.scala:125)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1223)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1221)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1244)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1242)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1246)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1241)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1249)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1214)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#sbt-link;2.2.3: not found
[error] unresolved dependency: com.typesafe.play#play-exceptions;2.2.3: not found
[error] unresolved dependency: com.typesafe.play#routes-compiler_2.10;2.2.3: not found
[error] unresolved dependency: com.typesafe.play#templates-compiler_2.10;2.2.3: not found
[error] unresolved dependency: com.typesafe.play#console_2.10;2.2.3: not found
[error] unresolved dependency: net.contentobjects.jnotify#jnotify;0.94: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

**Comment by unixtommy** [comment]
oh,No  wtf,2014

**Comment by unixtommy** [comment]
now ,I have the issue,add the Repo ,not work

**Comment by DaniloMurbach** [comment]
Oh, No wtf 2023
